# pull official base image
FROM node:14

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install -g --silent
RUN npm install -g install-peerdeps
RUN install-peerdeps --dev eslint-config-airbnb-base

# RUN npm install react-scripts@3.4.1 -g --silent
RUN chown -R node.node /app

RUN chmod 777 node_modules

EXPOSE 3000
# add app
COPY . ./


# start app
CMD ["npm", "start"]


# production environment
# FROM nginx:stable-alpine
# COPY --from=build /app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]