version: '3.8'

services:
  front-end:
    stdin_open: true
    restart: always
    container_name: ReactSomeCode
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
