version: '3.7'

services:
  front-end:
    restart: always
    container_name: ReactSomeCode
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    stdin_open: true
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
